import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {saveMeeting,archiveAdapter} from '../src/archive.mjs';
const openclawDir=process.env.OPENCLAW_TEAMS_OPENCLAW_DIR;
const root=await fs.mkdtemp(path.join(os.tmpdir(),'openclaw-teams-archive-'));
const dir=path.join(root,'three-speaker-fixture');await fs.mkdir(dir);
const meta={started:'2026-10-01T10:00:00Z',ended:'2026-10-01T10:01:00Z',audio_started_at:1790848800,status:'stopped'};
const transcript={engine:'fixture-not-speech-recognition',model:'synthetic-contract',created_at:new Date().toISOString(),execution_machine:os.hostname(),execution_location:'recording_mac',segments:[{start_ms:0,end_ms:1000,text:'This is a storage contract fixture.',source:'mic',speaker:'me',speaker_name:'Alex',attribution:'local_microphone'},{start_ms:2000,end_ms:3000,text:'A timestamped speaker observation supports this label.',source:'system',speaker:'system_1',speaker_name:'Blair',attribution:'meeting_tile'},{start_ms:4000,end_ms:5000,text:'Uncertain speech must remain unknown.',source:'system',speaker:'system_2',speaker_name:'Casey',attribution:'diarization'}]};
await fs.writeFile(path.join(dir,'meta.json'),JSON.stringify(meta));await fs.writeFile(path.join(dir,'transcript.json'),JSON.stringify(transcript));
const stateDir=path.join(root,'state');
const first=await saveMeeting(dir,{openclawDir,stateDir});
const second=await saveMeeting(dir,{openclawDir,stateDir});
assert.equal(first.sessionId,second.sessionId);assert.equal(second.utteranceCount,3);
const Store=await archiveAdapter(openclawDir);const store=new Store(path.join(stateDir,'transcripts'),{env:{...process.env,OPENCLAW_STATE_DIR:stateDir}});
const session=await store.readSession(first.sessionId);const rows=await store.readUtterancesForSession(session);
assert.deepEqual(rows.map(r=>r.speaker.label),['Alex','Blair','Unknown speaker']);
console.log(JSON.stringify({test:'actual OpenClaw canonical store, synthetic text fixture, not STT',stateDir,sessionId:first.sessionId,rows:rows.length,idempotent:true},null,2));
